### ISSUE TITLE
Set Fritzbox port

### ISSUE THREAD

**Issue by monza258** [Sunoo/homebridge-ftp-motion#1]
Hi, thanks for your Plugin. 

Can you tell me what I set to get the images from my fritzbox? 

Which port I must set? I use four cameras in four folders. 
Like: 
CAMS/Garten
CAMS/Haustuer
CAMS/Eingang
CAMS/Terrasse

Or can you include a option so set the ip and the folder name in fields?

Think we need also login check 
See image about login data. 

![image](https://user-images.githubusercontent.com/37027557/87868603-fcfe7280-c997-11ea-85a9-d1dd22b9c843.jpeg)

**Comment by Sunoo** [comment]
I do plan to add authentication, in its current state it is a VERY quick and dirty solution. The FTP port can be any value you want, as long as you configure it the same as whatever is uploading to this.

I’m not sure what you mean by being allowed to set the IP. The IP would be that of whatever device it is installed on.

**Comment by monza258** [comment]
My camera has the ip 48. 
My Fritzbox the 01. 
My Pi the 126. 

The plugin tries to get the pictures from the PI.  Or am I wrong?  I cannot get access without specifying the user and password.  
And I would have to tell the plugin on which device and folder the pictures are on the network.

**Comment by Sunoo** [comment]
The way I was writing the plugin, it would basically act as a proxy for the FTP traffic. Your cameras would upload the images to the server created by this.

I haven’t yet written the functionality to then either upload the images to another FTP server or save them locally, but that is my next step.

**Comment by monza258** [comment]
I tried to save the pictures on the pi using the camera setup.  Unfortunately does not work.  I would be dependent on the functionality of uploading to another server.  The plugin would only help me in this way.  Thanks for your work.

**Comment by Sunoo** [comment]
I plan to add that this week.

Currently the FTP server exposed by the plugin just triggers the motion alert and discards the image.

**Comment by monza258** [comment]
I am following it very curiously and am looking forward to this solution / extension.

**Comment by Sunoo** [comment]
FTP upload support has been added to this plugin. The information on configuration is on the main page.

**Comment by monza258** [comment]
Config like this: 

```
{
            "cameras": [
                {
                    "name": "Haustür",
                    "path": "CAMS/Haustuer",
                    "server": "192.168.0.1",
                    "port": "21",
                    "username": "fromfritzlogin",
                    "password": "loginpasswort",
                    "tls": false
                },
                {
                    "name": "Eingang2"
                }
            ],
            "name": "FTP Motion",
            "ftp_port": 5000,
            "http_port": 8080,
            "platform": "ftpMotion"
        }
    ]
```

**Comment by Sunoo** [comment]
Looks good, as long as you configure your camera properly to upload to the server exposed by this plugin.

**Comment by monza258** [comment]
I can't set the 
Server Address: PI of running pi (192.168.0.126)
Server Port: (21) 

on my Camera FTP setting. 

I get error to login: 

Test......Failed.Can not connect to the server
--

😬

**Comment by Sunoo** [comment]
According to your config, the server is running on port 5000, not port 21.

**Comment by monza258** [comment]
Even if I take port 5000 the error comes.

**Comment by monza258** [comment]
Cam can't connection sftp://    ??

**Comment by Sunoo** [comment]
I’m sorry I’m not sure I understand your question.

**Comment by monza258** [comment]
I mean that the camera can't save Pictures to raspberry pi as server. After set the options in camera I get an error.

I have contact you also by email. 😉

**Comment by Sunoo** [comment]
So the issue seemed to be some minor configuration errors as well as the ü in your camera name, which seems to be a limitation of FTP.

Best way I can “fix” this is probably just some improved documentation.
