### ISSUE TITLE
FTP no longer working

### ISSUE THREAD

**Issue by ucfhall** [Sunoo/homebridge-ftp-motion#124]
FTP appears to be no longer working on this plugin. FTP tests from two previously working cameras now fail and NETSTAT confirms that port 5000 (or whatever port is specified in the config) is not listening on the server.

**Comment by Sunoo** [comment]
What changed since you had it working? I can try to do some testing myself later tonight to see if I can replicate it, but it worked fine last time I pushed a version.

**Comment by ucfhall** [comment]
Nothing except maybe some updates to Debian. I’ve tried removing and reinstalling the plugin to no avail 

On Mar 29, 2021, at 19:09, David Maher ***@***.***> wrote:

﻿
What changed since you had it working? I can try to do some testing myself later tonight to see if I can replicate it, but it worked fine last time I pushed a version.

**Comment by Sunoo** [comment]
Are you getting any messaging in your logs from this plugin when Homebridge starts up?

**Comment by ucfhall** [comment]
None. I thought that was strange too. It appears to install successfully. 

On Mar 29, 2021, at 19:28, David Maher ***@***.***> wrote:

﻿
Are you getting any messaging in your logs from this plugin when Homebridge starts up?

**Comment by Sunoo** [comment]
Can you share your config? There should at least be some server starting type messages as it comes up, and if there wasn’t, I’d expect some sort of error stating why it couldn’t start.

**Comment by ucfhall** [comment]
FTP is mysteriously working now…but when I test the FTP upload from the camera I get this: [3/29/2021, 9:46:05 PM] [FTP Motion] [Entrance] [test20210329214605.txt] Error making HTTP call: Error: socket hang up


Here is the FTP Motion part of config.json

        {
            "name": "FTP Motion",
            "ftp_port": 5060,
            "override_http": 8081,
            "cameras": [
                {
                    "name": "Driveway",
                    "local_path": "/var/lib/homebridge/motion_images/Driveway"
                },
                {
                    "name": "Entrance",
                    "local_path": "/var/lib/homebridge/motion_images/Entrance"
                }
            ],
            "platform": "ftpMotion"
        }

**Comment by ucfhall** [comment]
Part of the problem I forgot to mention before:
[3/29/2021, 9:48:03 PM] [FTP Motion] Initializing ftpMotion platform...
[3/29/2021, 9:48:03 PM] [FTP Motion] You must have "porthttp" configured in the homebridge-camera-ffmpeg plugin.

I do have porthttp configured in homebridge-camera-ffmpeg as 8080. Whether I have 8080 or nothing in the FTP Motion config I still get the error I sent you earlier.

**Comment by Sunoo** [comment]
Can you share your full config? Maybe I can fix that in the next version. In the meantime, it should work if you set `override_http` in the config for this plugin.

**Comment by ucfhall** [comment]
This is resolved…sort of. I thought porthttp was filled in the FFMPEG plugin but it wasn’t. In the UI it has 8080 in grey text which I assumed meant it was in CONFIG.json but it wasn’t until I specifically typed it in to the field and applied. Everything works now but I cannot explain why the plugin was not even loading before. Here’s the full config.json. 
[config.json.zip](https://github.com/Sunoo/homebridge-ftp-motion/files/6225636/config.json.zip)

**Comment by Sunoo** [comment]
Ah, yea, that’d do it. I can change that to be blank instead of greeted out text in the next version, it’d probably be clearer.

Not sure why it wouldn’t have loaded before, but it’s hard to troubleshoot a problem that isn’t happening. I think I’ll close this out for now, but feel free to reopen it if it happens again.

**Comment by ucfhall** [comment]
Will do. Thanks for your effort and promptness, David.
