### ISSUE TITLE
Motion notification

### ISSUE THREAD

**Issue by clrmsc** [Sunoo/homebridge-ftp-motion#3]
Hi guys, motion notification works, if I use only esp32cam?

**Comment by felho001** [comment]
Only DCS 960L knows ftp! Da huta C46 not supported ftp. This is new config pls chek.
<img width="573" alt="Képernyőfotó 2020-07-22 - 20 05 33" src="https://user-images.githubusercontent.com/45117257/88212209-2c8ed280-cc57-11ea-875e-70a0d5864660.png">
<img width="614" alt="Képernyőfotó 2020-07-22 - 20 05 11" src="https://user-images.githubusercontent.com/45117257/88212213-30225980-cc57-11ea-8340-6bbc652e5d5b.png">
<img width="385" alt="Képernyőfotó 2020-07-22 - 20 05 20" src="https://user-images.githubusercontent.com/45117257/88212218-3284b380-cc57-11ea-9c58-63828e0dfcad.png">

**Comment by Sunoo** [comment]
Assuming that 192.168.1.40 is where your Homebridge is running, the only issue I see is that ‘Path’ on your camera should be ‘Nappali’.

**Comment by felho001** [comment]
it is my synology nas 192.168.1.40 patch is my nas file system home-kamera-napalli. When I tested dcs settings succsessfull save test image.

**Comment by Sunoo** [comment]
This plugin requires that you upload images to it. If you’re using the FTP upload feature of your camera to save images already, you’ll need to either need to wait for me to write support for that into this plugin, or wait until I finish the SMTP plugin so that you can use the Email ability of your camera instead.

**Comment by felho001** [comment]
Ok. I will be wait. Thx

**Comment by Sunoo** [comment]
I've added a plugin for using the email functionality, if you aren't currently using that feature of the camera, maybe this would be a better fit: https://github.com/Sunoo/homebridge-smtp-motion

**Comment by Sunoo** [comment]
FTP upload support has been added to this plugin. The information on configuration is on the main page.

**Comment by felho001** [comment]
I now sent new ftp motion settings for new version. I will see how to work...
