### ISSUE TITLE
amcrest camera

### ISSUE THREAD

**Issue by lukasa1993** [Sunoo/homebridge-ftp-motion#58]
```

[39m[31m[FTP Server] [Bunyan] Socket not writable[39m
[37m[10/5/2020, 6:40:09 PM] [39m[36m[FTP Motion] [39m[31m[FTP Server] [Bunyan] operation timed out[39m
[37m[10/5/2020, 6:40:09 PM] [39m[36m[FTP Motion] [39m[31m[FTP Server] [Bunyan] Socket not writable[39m
[37m[10/5/2020, 6:40:09 PM] [39m[36m[FTP Motion] [39m[31m[FTP Server] [Bunyan] Socket not writable[39m
[37m[10/5/2020, 6:40:09 PM] [39m[36m[FTP Motion] [39m[31m[FTP Server] [Bunyan] operation timed out[39m
[37m[10/5/2020, 6:40:09 PM] [39m[36m[FTP Motion]
```

cant seem to make it work thrue camera if i manually connect to ftp it seems to work but with camera this is log i get

**Comment by Sunoo** [comment]
Interesting, can you share your config?

**Comment by lukasa1993** [comment]
```
"accessories": [],
    "platforms": [
        {
            "name": "Camera FFmpeg",
            "porthttp": 18083,
            "cameras": [
                {
                    "name": "garage",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-xerror -rtsp_transport tcp -i rtsp://user:1234@192.168.1.117/cam/realmonitor?channel=1&subtype=0 -c:a aac -b:a 128k -c:v libx264 -b:v 2500k -preset superfast",
                        "stillImageSource": "-i http://user:1234@192.168.1.117/cgi-bin/snapshot.cgi",
                        "maxStreams": 4,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 0,
                        "forceMax": true,
                        "videoFilter": "none",
                        "audio": true,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "name": "Config",
            "port": 8083,
            "platform": "config"
        },
        {
            "name": "FTP Motion",
            "ftp_port": 5000,
            "http_port": 18083,
            "cameras": [
                {
                    "name": "garage",
                    "cooldown": 10,
                    "local_path": "/homebridge/ftp"
                }
            ],
            "platform": "ftpMotion"
        }
    ]
}
```

**Comment by owlsy1971** [comment]
ive got same issue 

[10/15/2020, 00:03:23] Homebridge v1.2.3 is running on port 51290.
[10/15/2020, 00:03:23] [FTP Motion] [FTP Server] Started on port 21.
[10/15/2020, 00:03:45] [FTP Motion] [FTP Server] [Bunyan] operation timed out
[10/15/2020, 00:03:45] [FTP Motion] [FTP Server] [Bunyan] Socket not writable
[10/15/2020, 00:04:01] [FTP Motion] [FTP Server] [Bunyan] operation timed out
[10/15/2020, 00:04:01] [FTP Motion] [FTP Server] [Bunyan] Socket not writable

any ideas

**Comment by Sunoo** [comment]
I haven’t been able to recreate the issue, which makes it difficult. I did however recently pick up an Amcrest camera, so I’ll try to get that set up soon and see.

**Comment by Sunoo** [comment]
I have so far been unable to reproduce this issue with my Amcrest camera, not sure what’s going on.

Amcrest cameras also support SMTP, maybe that would work for you?

**Comment by lukasa1993** [comment]
![Screen Shot 2020-10-26 at 18 09 06](https://user-images.githubusercontent.com/1499012/97182738-57d51080-17b6-11eb-9f04-f13011e6cb03.png)
these are my options so which you mean by smtp ?

**Comment by Sunoo** [comment]
Interesting, looks like you might not. What model is your camera?

**Comment by lukasa1993** [comment]
ip2m-841b

**Comment by Sunoo** [comment]
And the errors in your log happen when the camera tries to upload, right?

**Comment by lukasa1993** [comment]
yes

**Comment by v0r73x** [comment]
I have the same issue with an WIFI CAM (hlswifi). I tried with different Linux systems with home bridge and your plugin. On all write sockets issue as above. With a dlinkcam it works flawlessly. But snmp plugin also not worked for me unfortunately. Problem there is that the hlswifi cam not successfully finish the test connection.

**Comment by Sunoo** [comment]
Interesting, let me get some more FTP clients and see if I can recreate the issue somehow.

**Comment by lukasa1993** [comment]
any love for this ?

**Comment by Sunoo** [comment]
I have been unable to recreate the issue with anything I have available to me. I’m in the middle of moving right now, but I can try to look again when I get settled in the new place. It’s just a bit difficult, since I don’t have access to every model of camera on the market.
